version: 2.1
orbs:
  aws-s3: circleci/aws-s3@4.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.11.5
    environment:
      AWS_REGION: us-east-1
    steps:
      - checkout
      - run: python --version
      - run: npm install
      - run: npm run build
      - aws-s3/sync:
          from: dist
          to: 's3://demo-ci-cd-article-2/'
          args: >
            --acl public-read
            --cache-control "max-age=86400"
            --delete
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
